version: 2

sources:
  - name: raw_staff_data
    database: calibrate-data
    schema: staff
    tables:
      - name: raw_paycom
        description: "Raw staff data from paycom"
      - name: raw_bamboohr
        description: "Raw staff data from BambooHR"