from setuptools import find_packages, setup

setup(
    name="people_team_data",
    version="0.1.0",
    description="A Dagster project for managing people team data workflows.",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Jack Stehn",
    author_email="jack@caliberschools.org",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    packages=find_packages(exclude=["people_team_data_tests"]),
    install_requires=[
        "black",
        "dagit",
        "dagster",
        "dagster-cloud",
        "dagster-cloud-cli",
        "dagster-dbt",
        "dagster-dlt",
        "dagster-gcp",
        "dagster-gcp-pandas",
        "dagster-graphql",
        "dagster-pandas",
        "dagster-pipes",
        "dagster-postgres",
        "dagster-webserver",
        "dbt >= 1.9.0",
        "dbt-bigquery",
        "dbt-postgres",
        "dbt-python",
        "dlt[bigquery,filesystem,sqlalchemy,postgres]",
        "google-cloud-bigquery-storage",
        "google-api-python-client",
        "gspread",
        "isort",
        "pandas",
        "psutil",
        "psycopg2-binary",
        "pydantic",
        "requests",
        "streamlit",
        "tink",
    ],
    extras_require={
        "dev": ["dagster-webserver", "pytest", "black", "flake8", "mypy"]
    },
    python_requires=">=3.9,<3.13",
)
