# people_team_data/config/asset_configs.py
# Configurations related to Position Control assets
pc_positions_config = {
    "columns": {
        "Position_ID": "str",
        "Position_Unique": "bool",
        "Assignment_Count": "int",
        "Position_Start": "datetime64[ns]",
        "Position_End": "datetime64[ns]",
        "Position_Status": "str",
        "Position_HRDepartment": "str",
        "Position_HRDivision": "str",
        "Position_HRSubDepartment": "str",
        "Position_Code": "str",
        "Position_Count": "str",
        "Position_Name": "str",
        "Position_Account": "str",
        "Position_Goal": "str",
        "Position_Full": "str",
        "Position_Credential": "str",
        "Position_Supervisor": "str",
        "Position_Represented": "str",
        "Notes": "str",
    },
    "primary_key": "Position_ID",
    "non_null": ["Position_ID"],
}

pc_employees_config = {
    "columns": {
        "Employee_ID": "str",
        "Employee_InitialHireDate": "datetime64[ns]",
        "Employee_RehireDate": "datetime64[ns]",
        "Employee_EndDate": "datetime64[ns]",
        "Employee_Type": "str",
        "Employee_Status": "str",
        "Employee_FirstName": "str",
        "Employee_MiddleName": "str",
        "Employee_LastName": "str",
        "Employee_Email": "str",
        "Employee_Phone": "str",
        "Employee_YearsOfServiceStart": "str",
        "Employee_FullName": "str",
        "Employee_Full": "str",
        "Employee_SEID": "str",
        "Employee_Gender": "str",
        "Employee_Race": "str",
        "Employee_Hispanic": "str",
        "Employee_CALPADSStartYearCertificated": "str",
        "Employee_CALPADSCaliberStartYearCertificated": "str",
        "Notes": "str",
    },
    "primary_key": "Employee_ID",
    "non_null": ["Employee_ID"],
}

pc_adjustments_config = {
    "columns": {
        "Adjustment_ID": "str",  # Meant to be ID but is currently blank
        "Assignment_Full": "str",
        "Adjustment_Status": "str",
        "Adjustment_Category": "str",
        "Adjustment_Description": "str",
        "Adjustment_Salary": "currency",
        "Adjustment_Hourly": "currency",
        "Adjustment_Begin_Payroll": "datetime64[ns]",
        "Adjustment_End_Payroll": "datetime64[ns]",
        "Adjustment_#": "str",
        "Adjustment_PPP": "datetime64[ns]",
        "Notes": "str",
    },
    "non_null": ["Assignment_Full", "Adjustment_Status"],
    "foreign_keys": {
        "Assignment_Full": "position_control_assignments.Assignment_Full"
    },
}

pc_stipends_config = {
    "columns": {
        "Stipend_ID": "str",
        "Employee_ID": "str",
        "Employee_Name": "str",
        "Stipend_Start_Date": "datetime64[ns]",
        "Stipend_End_Date": "datetime64[ns]",
        "Stipend_Status": "str",
        "Stipend_Category": "str",
        "Stipend_Description": "str",
        "Stipend_Amount": "currency",
        "Stipend_FullAccount": "str",
        "Stipend_Account": "str",
        "Stipend_FullGoal": "str",
        "Stipend_Goal": "str",
        "Stipend_Location": "str",
        "Stipend_FullResource": "str",
        "Stipend_Resource": "str",
        "Notes": "str",
    },
    "non_null": ["Stipend_ID", "Employee_ID", "Employee_Name"],
    "primary_key": "Stipend_ID",
    "foreign_keys": {"Employee_ID": "position_control_employees.Employee_ID"},
}

pc_assignments_config = {
    "columns": {
        "Assignment_ID": "str",
        "Assignment_Start": "datetime64[ns]",
        "Assignment_End": "datetime64[ns]",
        "Assignment_Count": "int",
        "Assignment_Status": "str",
        "Position_ID": "str",
        "Position_Full": "str",
        "Employee_ID": "str",
        "Employee_Count": "int",
        "Employee_Full": "str",
        "Assignment_Full": "str",
        "Assignment_FTE": "float",
        "Assignment_Calendar": "int",
        "Assignment_Scale": "str",
        "Assignment_Step": "int",
        "Employee_YearsOfServiceStart": "str",
        "Assignment_Column": "str",
        "Assignment_Salary": "currency",
        "Assignment_Wage": "currency",
        "Assignment_PPP": "currency",
        "Position_Account": "str",
        "Position_Goal": "str",
        "Assignment_Resource": "str",
        "Assignment_FullResource": "str",
        "Notes": "str",
    },
    "primary_key": "Assignment_ID",
    "non_null": ["Assignment_ID"],
    "foreign_keys": {
        "Position_ID": "position_control_positions.Position_ID",
        "Employee_ID": "position_control_employees.Employee_ID",
    },
}

paycom_config = {
    "Hire_Date": "datetime64[ns]",
    "Rehire_Date": "datetime64[ns]",
    "Termination_Date": "datetime64[ns]",
    "Salary": "currency",
    "Rate_1": "currency",
    "Annual_Salary": "currency",
}
